### ISSUE TITLE
Cases are to small.

### ISSUE THREAD

**Issue by MrMcJosh18** [Krysiek/Pucirion#1]
The cases do not match the Hyperion's original size, so the lids or tray will not fit. additionally there is no case option for the 804040 battery type. is there any way the size could at least be fixed the battery option is not that big of an issue.

Below i will show some pictures of what i mean. ty for your time.

![image_2024-08-07_030123893](https://github.com/user-attachments/assets/48527420-880d-4d83-803a-7498c3b33795)
![image_2024-08-07_030202628](https://github.com/user-attachments/assets/18234d3e-868f-4230-a66d-b4ca170ae641)

**Comment by l0ud** [comment]
Hi, I know this response is very late but... they fit. You're comparing to 804040 Hyperion which is significantly bigger than 503759 version. This remix contains files only compatible with 503759 variants:
https://github.com/Smeltie/Hyperion/tree/main/STL%20Files/503759
https://github.com/Smeltie/Hyperion/tree/main/STL%20Files/503759_SS22F32

804040 version was skipped because, quite frankly, Hyperion is not really optimal for such batteries (a lot of wasted space)

**Comment by MrMcJosh18** [comment]
Hey! Thank You for the responce,I found out later I was just being dumb and
just forgot to remove my post i apologize. thank you for your responce
thoigh.
